### ISSUE TITLE
[PE-D][Tester D] Bug in Delete Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-F10-1/tp#101]
![Screenshot 2023-03-31 at 4.50.16 PM.png](https://raw.githubusercontent.com/chokyao/ped/main/files/1f97724c-6ad6-4fb3-80c7-f7ad568d55cb.png)

The delete command does not seem to be working.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: chokyao/ped#1

**Comment by mitchmalvin1** [comment]
There is a bug in the user guide, `card delete -i" is supposed to use index. Fixed in commit `cd812cbfa2bc02326c493274d4c28ab74b44d169`
