### ISSUE TITLE
[PE-D][Tester C] More professional examples in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-F10-1/tp#103]
Users would appreciate a more professional expected output in the UG that reflects the proper usage of the application.

![Screenshot 2023-03-31 at 4.56.09 PM.png](https://raw.githubusercontent.com/T-Wan-Lin/ped/main/files/9d61798e-f89e-47fb-82be-2c20cbe9c55f.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: T-Wan-Lin/ped#4

**Comment by mitchmalvin1** [comment]
Fixed in `a278b6864d59791da03efbd7579e5ac35e8b08ab `
