### ISSUE TITLE
[PE-D][Tester C] Exception not thrown when user adds a card in the wrong format

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F10-1/tp#104]
![Screenshot 2023-03-31 at 4.59.10 PM.png](https://raw.githubusercontent.com/T-Wan-Lin/ped/main/files/ecc9bba4-abb2-430e-8425-5b56eb3922eb.png)

The user is able to add a card even though the flag order in `card add` command is swapped.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: T-Wan-Lin/ped#5

**Comment by mitchmalvin1** [comment]
Fix UG to reflect that flags can be listed in any order.
