### ISSUE TITLE
[PE-D][Tester D] Deck name cannot have spaces

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F10-1/tp#106]
![Screenshot 2023-03-31 at 5.01.35 PM.png](https://raw.githubusercontent.com/chokyao/ped/main/files/d8294b5a-09d5-4aba-8f54-e4ccbe82e6c0.png)
When I attempt to put more than a single word in a deck name, only the first word is registered.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: chokyao/ped#2

**Comment by ltzehan** [comment]
Covered in #144
