### ISSUE TITLE
[PE-D][Tester B] Certain card questions and answers are not parsed correctly

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F10-1/tp#108]
in the `card add` command, the arguments for `-q` and `-a` cannot be "-q" and "-a". Considering the context of this app, where these flag names may be valid questions and answers for math-related subjects, the command parsing may have to be modified.

![bug2.PNG](https://raw.githubusercontent.com/GraceZhuXY/ped/main/files/94a8c784-a974-428d-b4de-9b634168bbdf.PNG)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: GraceZhuXY/ped#2

**Comment by lihka1202** [comment]
@ltzehan I don't think the "-q" and "-a" thing is an issue, and it seems like the displaying of "null" is the only issue.

To address the tester's question, we can probably clarify in the UG about the usage of "-q" and "-a" as potential questions and answers. We can suggest to the user that if they want to put in math questions, then they can use "Q: " and "A: " or something instead.

**Comment by ltzehan** [comment]
> @ltzehan I don't think the "-q" and "-a" thing is an issue, and it seems like the displaying of "null" is the only issue.
> 
> To address the tester's question, we can probably clarify in the UG about the usage of "-q" and "-a" as potential questions and answers. We can suggest to the user that if they want to put in math questions, then they can use "Q: " and "A: " or something instead.

I think what they mean is that the user may want to use tokens that resemble the flags themselves in the question/answer, e.g.

Q: How do I specify a question
A: Using the -q flag

We could try using some escape character, but this is such a niche use case that maybe we should just point out that this isn't supported in UG

**Comment by ltzehan** [comment]
Will need to put a note in the UG to tell the user to manually quote these characters
