### ISSUE TITLE
[PE-D][Tester C] Application permits invalid commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-F10-1/tp#120]
![Screenshot 2023-03-31 at 5.19.33 PM.png](https://raw.githubusercontent.com/T-Wan-Lin/ped/main/files/f491fa59-41d1-414a-a7a7-ae8fb0d9014c.png)

In the case of invalid user input for the `card list` command, the application does not throw an exception.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: T-Wan-Lin/ped#9

**Comment by ltzehan** [comment]
Closed with #144
