### ISSUE TITLE
[PE-D][Tester E] typing an invalid UUID string  crashes the program

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-F10-1/tp#139]
![image.png](https://raw.githubusercontent.com/hyperbola-bear/ped/main/files/26bd23c8-4673-4969-baa1-ca0c8aaa4e34.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: hyperbola-bear/ped#1

**Comment by mitchmalvin1** [comment]
Fixed
