### ISSUE TITLE
tP Code Review - Mitch Malvin

### ISSUE THREAD

**Issue by wamikamalik** [AY2223S2-CS2113-F10-1/tp#147]
Hi @mitchmalvin1! Good job on contributing to the tP. Following are the few comments I have:

- [ ] Consider removing comments that are private notes to yourself. See example marked in red below.
<img src="https://user-images.githubusercontent.com/60306071/229301398-499f0fe0-97a9-4d5e-93f4-9a18d59992e1.png" width = 500>

- [ ] Consider refactoring this return statement to make it more readable. 
![image](https://user-images.githubusercontent.com/60306071/229301597-319c8430-670a-472e-97d3-c366860a575c.png)

- [ ] Consider shortening your method and class names. Examples below.
<img src = "https://user-images.githubusercontent.com/60306071/229302522-c88d0f5e-f1ef-4064-bb84-cefa0a45e21c.png" width = 600>
<img src="https://user-images.githubusercontent.com/60306071/229302544-879d0d9b-71d3-4ff0-b93a-e2f4306ae8e9.png" width = 600>

**Comment by mitchmalvin1** [comment]
fixed
