### ISSUE TITLE
tP Code Review - Muthya Narayanachary Akhil

### ISSUE THREAD

**Issue by wamikamalik** [AY2223S2-CS2113-F10-1/tp#148]
Hi @lihka1202! Good job on contributing to the tP. Following are a few comments I have:

- [x] Consider refactoring magic literals such as "c", "t", "o", "n". 

- [x] Consider using standard spacing in your code, for instance, see below.
![image](https://user-images.githubusercontent.com/60306071/229303081-7349f39a-6572-44cc-b469-4f9ec511146c.png)

- [x] Consider removing comments that are that are private notes to yourself or any commented out code. See examples below.
![image](https://user-images.githubusercontent.com/60306071/229303149-8db2dbe4-475b-4419-864f-3c5a8464d02a.png)
![image](https://user-images.githubusercontent.com/60306071/229303298-1d3b6291-524c-4994-9a80-5d3e76b30a2f.png)

- [x] Consider providing short yet understandable and readable names to your methods and classes. Some names are too long. See example below.
![image](https://user-images.githubusercontent.com/60306071/229303255-1f28749c-c42a-46c6-8531-47278219460c.png)

**Comment by lihka1202** [comment]
Noted!, I'll try to ensure these changes are fixed!
