### ISSUE TITLE
tP Code Review - Teng Yuan-Kai

### ISSUE THREAD

**Issue by wamikamalik** [AY2223S2-CS2113-F10-1/tp#149]
Hi @iantenkai! Good job on contributing to the tP. Following are a few comments I have:

- [x] Please avoid very long methods. For instance the method load() in _JsonStorage.java_ is quite long and can easily be refactored. Consider separating this into multiple methods.

- [x] Consider refactoring magic literals like "uuid", "tags", "question".

- [x]  Consider removing comments that are private notes to yourself. See examples below.
![image](https://user-images.githubusercontent.com/60306071/229303957-337965b0-a95d-4cc4-af77-eb76fff4728b.png)

**Comment by iantenkai** [comment]
I'll take note of the suggestions, thank you! I've been planning to refactor the code in JsonStorage
