### ISSUE TITLE
Fix logic issues

### ISSUE THREAD

**Issue by ltzehan** [AY2223S2-CS2113-F10-1/tp#189]
Broken logic; need to be fixed to pass tests. Refer to `LogicTest` added in #188

**Comment by ltzehan** [comment]
`logic_noDoubleDelete_deleteByUuidFirst`:
Card is added via both Tag and CardUUID, but when both the tag and CardUUID are deleted from the deck, the card still remains in the deck (c.f. `logic_noDoubleDelete_deleteByTagFirst`)

**Comment by ltzehan** [comment]
`logic_addByTagDeleteByCardUUID`:
Card that is added by tag should not be deletable by CardUUID (✔️ passes), but the exception message is "The card is not in the deck" which may be confusing to users

**Comment by lihka1202** [comment]
> `logic_noDoubleDelete_deleteByUuidFirst`: Card is added via both Tag and CardUUID, but when both the tag and CardUUID are deleted from the deck, the card still remains in the deck (c.f. `logic_noDoubleDelete_deleteByTagFirst`)

Issue sorted locally, will update when committed to the PR.
