### ISSUE TITLE
Missing Stuff in the UG

### ISSUE THREAD

**Issue by lihka1202** [AY2223S2-CS2113-F10-1/tp#210]
Missing Suff:
- Editing Card
- Editing Tag

**Comment by mitchmalvin1** [comment]
Edit tag name is already there, for card, we never had that feature to begin with? @lihka1202

**Comment by ltzehan** [comment]
@lihka1202 looks like the deck stuff in UG are not yet updated or have inconsistencies with the rest of the UG's format, can you look into that thanks
