### ISSUE TITLE
Should we leave `Export` as it is?

### ISSUE THREAD

**Issue by lihka1202** [AY2223S2-CS2113-F10-1/tp#36]
The `Export` command is only performed if the user specifies it.

There are some Pros and Cons to this:

Pros
- The user can decide when to export the card list after modifying it as much as they want.

Cons
- The user must remember to export the document each time, and the automatic load and save component is lost. @ltzehan suggested that we export before exiting the program every time; this seems fair.

**Comment by mitchmalvin1** [comment]
I think auto-exporting before the program exits seems better considering how whenever user adds new cards, it will most likely be a bunch at once so there is no point to only export at a certain point. From the perspective of the user, having to manually export provides little to no benefit but it brings quite a bit of inconvenience.

**Comment by ltzehan** [comment]
Another way we could do this is to put the save file somewhere else, i.e.,

- Adding/deleting cards updates a "hidden" save file in AppData (or some application storage location)
- Export/Import commands will load from/write to application storage the user specified file (our current `savedata.json`)

Usage wise, this also makes more sense as the user is less likely to accidentally corrupt their saved data
