### ISSUE TITLE
(Stretch Goal) `Deck` should also be able to aggregate `Card` based on a list of `TagUUID`

### ISSUE THREAD

**Issue by ltzehan** [AY2223S2-CS2113-F10-1/tp#52]

**Comment by lihka1202** [comment]
Just a clarification: Does this mean we just need to create a deck for each 'tagUUID'?

**Comment by ltzehan** [comment]
Should be careful that we do not duplicate cards that are added both through CardUUID and TagUUID. Consider:

Card 1 (tags: [tag-1, tag-2])

Deck created with cards:
- By CardUUID: [Card 1]
- By TagsUUID: [tag-1. tag-2]

The deck must be able to de-duplicate a card with multiple included tags, **and** a card included by its ID and its tags

**Comment by lihka1202** [comment]
> Should be careful that we do not duplicate cards that are added both through CardUUID and TagUUID. Consider:
> 
> 
> 
> Card 1 (tags: [tag-1, tag-2])
> 
> 
> 
> Deck created with cards:
> 
> - By CardUUID: [Card 1]
> 
> - By TagsUUID: [tag-1. tag-2]
> 
> 
> 
> The deck must be able to de-duplicate a card with multiple included tags, **and** a card included by its ID and its tags

A BiMap can solve this I think

**Comment by ltzehan** [comment]
> > Should be careful that we do not duplicate cards that are added both through CardUUID and TagUUID. Consider:
> > Card 1 (tags: [tag-1, tag-2])
> > Deck created with cards:
> > 
> > * By CardUUID: [Card 1]
> > * By TagsUUID: [tag-1. tag-2]
> > 
> > The deck must be able to de-duplicate a card with multiple included tags, **and** a card included by its ID and its tags
> 
> A BiMap can solve this I think

I think at the very least we could use build a `HashSet` of all the CardUUID. I think having bidirectional mapping might be a performance-centered story on it's own
