### ISSUE TITLE
If an instance of `Card` has been deleted, its UUID could be deleted from all instances of `Decks` and `Tags` it is under

### ISSUE THREAD

**Issue by lihka1202** [AY2223S2-CS2113-F10-1/tp#59]
This is more of a suggestion for the time being, as the existing `Tag` structure already has check in place for this, but this is more for the future.

**Comment by mitchmalvin1** [comment]
You mean remove the card uuid from `Tags`? is it a typo? @lihka1202

**Comment by lihka1202** [comment]
> You mean remove the card uuid from `Tags`? is it a typo? @lihka1202 

Yep, my bad! I'll modify the heading

**Comment by lihka1202** [comment]
Issue fixed in commit 693132b
