### ISSUE TITLE
Inconsistent UX in parser

### ISSUE THREAD

**Issue by ltzehan** [AY2223S2-CS2113-F10-1/tp#72]
Different parser commands ask for different ways of identifying the same object. For example, 
- `Card` can be referred to by `CardUUID` or index
- `Tag` can be referred to by `TagUUID` or tag name
- `Deck` can be referred to by `DeckUUID` or deck name

We should either decide on **a common** representation OR allow the user to use either flag. E.g.,
`tag delete -t <tagName>` OR `tag delete -i <tagId>`

**Comment by lihka1202** [comment]
I think the best case possibility would be to allow the user to do both
